# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3
language: objective-c

before_install:
- gem install swiftlint
- gem install cocoapods
- pod repo update

script:
- swiftlint
- cocoapods lib lint --allow-warnings
